/**
 * `request-attachment-upload` / `request-attachment-download` — the two
 * MCP mint tools generated by `generateMcpTools` (see mcp.ts's
 * `GenerateMcpToolsOpts.attachmentTickets`). Exercises the "tools omitted
 * when unwired" contract (D10) and the mint-time policy (note/attachment
 * resolution, tag-scope, size cap, extension blocklist) against a fake
 * in-memory `AttachmentTicketProvider` — the spend side (actually writing
 * bytes) is bun-only and covered in src/attachment-tickets.test.ts.
 */

import { describe, test, expect, beforeEach } from "bun:test";
import { Database } from "bun:sqlite";
import { BunSqliteStore } from "./store.ts";
import { generateMcpTools, type McpToolDef } from "./mcp.ts";
import type { AttachmentTicket, AttachmentTicketProvider } from "./attachment/tickets.ts";
import { MAX_TICKET_UPLOAD_BYTES } from "./attachment/tickets.ts";
import type { Note } from "./types.ts";

class FakeTicketProvider implements AttachmentTicketProvider {
  tickets = new Map<string, AttachmentTicket>();
  async put(t: AttachmentTicket): Promise<void> {
    this.tickets.set(t.id, t);
  }
  async take(id: string): Promise<AttachmentTicket | null> {
    const t = this.tickets.get(id);
    if (!t) return null;
    this.tickets.delete(id);
    return t;
  }
}

let store: BunSqliteStore;

beforeEach(() => {
  store = new BunSqliteStore(new Database(":memory:"));
});

function findTool(tools: McpToolDef[], name: string): McpToolDef {
  const t = tools.find((x) => x.name === name);
  if (!t) throw new Error(`tool "${name}" not found`);
  return t;
}

async function callTool(tool: McpToolDef, params: Record<string, unknown>): Promise<any> {
  return await tool.execute(params);
}

async function expectToolError(tool: McpToolDef, params: Record<string, unknown>): Promise<any> {
  try {
    await tool.execute(params);
    throw new Error("expected the tool to throw");
  } catch (err) {
    return err as any;
  }
}

describe("D10 — tools omitted when unwired", () => {
  test("no attachmentTickets opt → neither ticket tool is generated", () => {
    const tools = generateMcpTools(store);
    expect(tools.find((t) => t.name === "request-attachment-upload")).toBeUndefined();
    expect(tools.find((t) => t.name === "request-attachment-download")).toBeUndefined();
  });

  test("attachmentTickets opt provided → both ticket tools are generated with the right verbs", () => {
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const upload = findTool(tools, "request-attachment-upload");
    const download = findTool(tools, "request-attachment-download");
    expect(upload.requiredVerb).toBe("write");
    expect(download.requiredVerb).toBe("read");
  });
});

describe("request-attachment-upload — mint", () => {
  test("happy path: returns the ticket envelope and stores a matching provider record", async () => {
    const note = await store.createNote("# Target\n", { path: "target" });
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const tool = findTool(tools, "request-attachment-upload");

    const before = Date.now();
    const result = await callTool(tool, { note: note.id, filename: "photo.png", size_bytes: 1024 });
    expect(result.method).toBe("PUT");
    expect(result.url).toMatch(/^https:\/\/host\/vault\/v1\/tickets\/[0-9a-f]{64}$/);
    expect(result.headers["content-type"]).toBe("image/png");
    expect(result.max_bytes).toBe(1024);
    expect(result.curl_example).toContain("curl -X PUT");
    expect(result.curl_example).toContain(result.url);

    const ticketId = result.url.split("/tickets/")[1] as string;
    const stored = provider.tickets.get(ticketId)!;
    expect(stored.kind).toBe("upload");
    expect(stored.noteId).toBe(note.id);
    expect(stored.filename).toBe("photo.png");
    expect(stored.mimeType).toBe("image/png");
    expect(stored.sizeBytes).toBe(1024);
    expect(stored.vaultName).toBe("v1");
    // TTL for a 1024-byte (<1 MiB) declared size is the 10-minute base.
    expect(stored.expiresAt - before).toBeGreaterThanOrEqual(10 * 60 * 1000 - 1000);
    expect(stored.expiresAt - before).toBeLessThanOrEqual(10 * 60 * 1000 + 5000);
  });

  test("mime_type is inferred from the filename extension when omitted", async () => {
    const note = await store.createNote("# T\n", { path: "t2" });
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const result = await callTool(findTool(tools, "request-attachment-upload"), {
      note: note.id,
      filename: "notes.csv",
      size_bytes: 10,
    });
    expect(result.headers["content-type"]).toBe("text/csv; charset=utf-8");
  });

  test("transcribe: true rides through to the stored ticket", async () => {
    const note = await store.createNote("# T\n", { path: "t3" });
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const result = await callTool(findTool(tools, "request-attachment-upload"), {
      note: note.id,
      filename: "memo.wav",
      size_bytes: 10,
      transcribe: true,
    });
    const ticketId = result.url.split("/tickets/")[1] as string;
    expect(provider.tickets.get(ticketId)!.transcribe).toBe(true);
  });

  test("missing note / filename / size_bytes → missing_required_field with how_to", async () => {
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const tool = findTool(tools, "request-attachment-upload");

    const e1 = await expectToolError(tool, { filename: "a.png", size_bytes: 1 });
    expect(e1.error_type).toBe("missing_required_field");
    expect(e1.field).toBe("note");
    expect(typeof e1.how_to).toBe("string");

    const e2 = await expectToolError(tool, { note: "x", size_bytes: 1 });
    expect(e2.error_type).toBe("missing_required_field");
    expect(e2.field).toBe("filename");

    const e3 = await expectToolError(tool, { note: "x", filename: "a.png" });
    expect(e3.error_type).toBe("invalid_query");
    expect(e3.field).toBe("size_bytes");
  });

  test("size_bytes over the 100 MiB cap → file_too_large with limit/got/how_to", async () => {
    const note = await store.createNote("# T\n", { path: "t4" });
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const err = await expectToolError(findTool(tools, "request-attachment-upload"), {
      note: note.id,
      filename: "huge.zip",
      size_bytes: MAX_TICKET_UPLOAD_BYTES + 1,
    });
    expect(err.error_type).toBe("file_too_large");
    expect(err.limit).toBe(MAX_TICKET_UPLOAD_BYTES);
    expect(err.got).toBe(MAX_TICKET_UPLOAD_BYTES + 1);
    expect(typeof err.how_to).toBe("string");
    expect(provider.tickets.size).toBe(0);
  });

  test("blocked (active-content) extension → blocked_upload_extension, no ticket minted", async () => {
    const note = await store.createNote("# T\n", { path: "t5" });
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const err = await expectToolError(findTool(tools, "request-attachment-upload"), {
      note: note.id,
      filename: "evil.html",
      size_bytes: 10,
    });
    expect(err.error_type).toBe("blocked_upload_extension");
    expect(err.extension).toBe(".html");
    expect(provider.tickets.size).toBe(0);
  });

  test("unknown note → not_found", async () => {
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const err = await expectToolError(findTool(tools, "request-attachment-upload"), {
      note: "does-not-exist",
      filename: "a.png",
      size_bytes: 10,
    });
    expect(err.error_type).toBe("not_found");
  });

  test("tag-scoped noteVisible: false → uniform not_found (no existence oracle)", async () => {
    const note = await store.createNote("# T\n", { path: "t6" });
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: {
        provider,
        vaultName: "v1",
        urlBase: "https://host/vault/v1",
        noteVisible: async (_n: Note) => false,
      },
    });
    const err = await expectToolError(findTool(tools, "request-attachment-upload"), {
      note: note.id,
      filename: "a.png",
      size_bytes: 10,
    });
    expect(err.error_type).toBe("not_found");
    expect(provider.tickets.size).toBe(0);
  });
});

describe("request-attachment-download — mint", () => {
  test("happy path: returns the ticket envelope with mime_type + known size, stores a matching provider record", async () => {
    const note = await store.createNote("# T\n", { path: "t7" });
    const attachment = await store.addAttachment(note.id, "2026-07-17/x.png", "image/png", { size: 42 });
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const result = await callTool(findTool(tools, "request-attachment-download"), {
      attachment_id: attachment.id,
    });
    expect(result.method).toBe("GET");
    expect(result.mime_type).toBe("image/png");
    expect(result.size_bytes).toBe(42);
    expect(result.curl_example).toContain(result.url);

    const ticketId = result.url.split("/tickets/")[1] as string;
    const stored = provider.tickets.get(ticketId)!;
    expect(stored.kind).toBe("download");
    expect(stored.attachmentId).toBe(attachment.id);
  });

  test("mime_type is derived from the path, not the caller-asserted row mime (vault#617)", async () => {
    const note = await store.createNote("# T\n", { path: "t7-mime" });
    const attachment = await store.addAttachment(note.id, "2026-07-17/photo.png", "text/html", { size: 42 });
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const result = await callTool(findTool(tools, "request-attachment-download"), {
      attachment_id: attachment.id,
    });
    expect(result.mime_type).toBe("image/png");
    const ticketId = result.url.split("/tickets/")[1] as string;
    expect(provider.tickets.get(ticketId)!.mimeType).toBe("image/png");
  });

  test("missing attachment_id → missing_required_field", async () => {
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const err = await expectToolError(findTool(tools, "request-attachment-download"), {});
    expect(err.error_type).toBe("missing_required_field");
  });

  test("unknown attachment → not_found", async () => {
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: { provider, vaultName: "v1", urlBase: "https://host/vault/v1" },
    });
    const err = await expectToolError(findTool(tools, "request-attachment-download"), {
      attachment_id: "does-not-exist",
    });
    expect(err.error_type).toBe("not_found");
  });

  test("tag-scoped noteVisible: false on the owning note → not_found, same shape as unknown attachment", async () => {
    const note = await store.createNote("# T\n", { path: "t8" });
    const attachment = await store.addAttachment(note.id, "2026-07-17/y.png", "image/png");
    const provider = new FakeTicketProvider();
    const tools = generateMcpTools(store, {
      attachmentTickets: {
        provider,
        vaultName: "v1",
        urlBase: "https://host/vault/v1",
        noteVisible: async (_n: Note) => false,
      },
    });
    const err = await expectToolError(findTool(tools, "request-attachment-download"), {
      attachment_id: attachment.id,
    });
    expect(err.error_type).toBe("not_found");
    expect(provider.tickets.size).toBe(0);
  });
});
