/**
 * Shared daemon-wrapper plumbing used by the macOS launchd and Linux
 * systemd install paths.
 *
 * Rationale: both platforms historically hardcoded the absolute path to
 * `src/server.ts` into their respective service/wrapper files at init
 * time. When the repo moved, the service kept respawning bun on a missing
 * file and crash-looped silently into `~/.parachute/vault/vault.err`.
 *
 * The fix: a small bash wrapper (`~/.parachute/vault/start.sh`) and a
 * pointer file (`~/.parachute/vault/server-path`) that the wrapper reads
 * at every boot. Moving the repo now only requires re-running
 * `parachute-vault init` — no plist/unit re-registration needed. Callers
 * can override the path for a single boot via `PARACHUTE_VAULT_SERVER_PATH`
 * in `~/.parachute/vault/.env`.
 */

import { homedir } from "os";
import { join, resolve, dirname } from "path";
import { writeFile, unlink } from "fs/promises";
import { existsSync, readFileSync } from "fs";
import { VAULT_HOME, ENV_PATH } from "./config.ts";

/** Start-up script sourced by launchd and systemd alike. */
export const WRAPPER_PATH = join(VAULT_HOME, "start.sh");
/** Pointer file. Contents: absolute path to `server.ts`, one line. */
export const SERVER_PATH_FILE = join(VAULT_HOME, "server-path");

/**
 * Build the start.sh contents. Pure string builder — easy to assert on.
 *
 * The generated script:
 *   1. Sources the user's login shell profiles to pick up PATH (needed
 *      when the daemon shells out to tools like ffmpeg, parakeet-mlx).
 *   2. Sources ~/.parachute/vault/.env.
 *   3. Resolves the server path: env override first, then pointer file.
 *   4. Fails loudly with an actionable message if the path is missing or
 *      the target file doesn't exist — instead of silently respawning
 *      into a crash loop the way a bare `bun /missing/path` would.
 *   5. Execs bun against the resolved server path.
 */
export function generateWrapper(opts: {
  bunPath: string;
  envPath?: string;
  serverPathFile?: string;
}): string {
  const envPath = opts.envPath ?? ENV_PATH;
  const pointer = opts.serverPathFile ?? SERVER_PATH_FILE;
  return `#!/bin/bash
# Auto-generated by \`parachute-vault init\`. Do not edit by hand — edits
# are clobbered on the next init. To override the server path for a
# single boot, set PARACHUTE_VAULT_SERVER_PATH in ~/.parachute/vault/.env.
# To point at a different repo permanently, re-run \`parachute-vault init\`
# from that repo.

set -u

# Source user shell profile for PATH (needed for parakeet-mlx, ffmpeg, etc.)
# Temporarily disable -u around these: user rc files routinely reference
# unbound variables (zsh plugin frameworks, conditional setups), and a bare
# \`set -u\` source would crash the wrapper with exit 1 and leave vault.err
# empty because of the 2>/dev/null below — launchd would respawn silently
# until it gave up. Keep the stderr redirect so expected "command not found"
# noise from incomplete setups doesn't fill vault.err; to debug silent
# wrapper failures, run \`bash -x ~/.parachute/vault/start.sh\` by hand.
set +u
[ -f "$HOME/.zprofile" ] && source "$HOME/.zprofile" 2>/dev/null
[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc" 2>/dev/null
set -u

if [ -f "${envPath}" ]; then
  set -a
  source "${envPath}"
  set +a
fi

# Resolve server path: env override wins, then pointer file written by init.
SERVER_PATH="\${PARACHUTE_VAULT_SERVER_PATH:-}"
if [ -z "$SERVER_PATH" ] && [ -f "${pointer}" ]; then
  SERVER_PATH=$(cat "${pointer}")
fi

if [ -z "$SERVER_PATH" ]; then
  echo "parachute-vault: server path not configured (no ${pointer} and PARACHUTE_VAULT_SERVER_PATH is unset)." >&2
  echo "parachute-vault: run \\\`parachute-vault init\\\` to configure it." >&2
  exit 1
fi

if [ ! -f "$SERVER_PATH" ]; then
  echo "parachute-vault: server.ts not found at $SERVER_PATH" >&2
  echo "parachute-vault: the repo may have moved. Run \\\`parachute-vault init\\\` from the current repo location." >&2
  exit 1
fi

exec "${opts.bunPath}" "$SERVER_PATH"
`;
}

/**
 * Resolve the absolute path to server.ts for the currently-running CLI.
 * Works for both `bun src/cli.ts` (dev) and `bun x @openparachute/vault`
 * (published) — whichever path the CLI loaded from, server.ts sits next to it.
 *
 * NOTE: this relies on `server.ts` shipping next to `cli.ts` in the
 * published package. If a `"files"` allowlist is ever added to
 * package.json, `src/server.ts` must be included explicitly.
 */
export function resolveServerPath(): string {
  return resolve(dirname(import.meta.path), "server.ts");
}

/** Write the wrapper script and pointer file together. Idempotent. */
export async function writeDaemonWrapper(): Promise<{ serverPath: string; bunPath: string }> {
  const serverPath = resolveServerPath();
  const bunPath = Bun.which("bun") || join(homedir(), ".bun", "bin", "bun");

  await writeFile(SERVER_PATH_FILE, serverPath + "\n");
  await writeFile(WRAPPER_PATH, generateWrapper({ bunPath }), { mode: 0o755 });

  return { serverPath, bunPath };
}

/** Remove the wrapper and pointer. Leaves .env, DB, logs alone. */
export async function removeDaemonWrapper(): Promise<void> {
  for (const p of [WRAPPER_PATH, SERVER_PATH_FILE]) {
    try {
      await unlink(p);
    } catch {
      // Not there — fine.
    }
  }
}

/**
 * Read the pointer file, returning null if it's missing or unreadable.
 * Used by the `vault doctor` / `vault uninstall` commands in PR 3 to tell
 * whether the daemon is pointing at a real file.
 */
export function readServerPathPointer(): string | null {
  try {
    if (!existsSync(SERVER_PATH_FILE)) return null;
    return readFileSync(SERVER_PATH_FILE, "utf8").trim() || null;
  } catch {
    return null;
  }
}
